<?php

namespace Database\Seeders;

use App\Models\Peserta;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $peserta = [
            0 => [
                'nama_lengkap' => 'Dr. Indrapratin E.H.N. Purukan, M.MT',
                'nip' => '197411292000031004',
                'ndh' => '55',
                'jabgol' => 'Kadis Perhubungan / Pembina Utama Muda IVc',
                'alamat' => 'Perum Pemda No.46 Kelurahan Paseng Kecamatan Siau Barat Kabupaten Kep. Sitaro',
                'hp' => '0811502417',
                'instansi' => 'Pemerintah Kabupaten Kepulauan Siau Tagulandang Biaro',
                'judul_laporan' => 'ESA-TranS, Excellent Service of SitAro Transportation System',
                'file_laporan' => 'https://drive.google.com/open?id=1tCub70U36Ry7Sv7fReR_b5yK0P2u-A_8',
                'pesan' => '-',
                'kesan' => '-',
            ],
            1 => [
                'nama_lengkap' => 'Drs. Dewa Gde Juli Artabrata',
                'nip' => '196807291993031006',
                'ndh' => '38',
                'jabgol' => 'Kepala Dinas IV C',
                'alamat' => 'Jl Jayagiri XVII no 11 B',
                'hp' => '081239158384',
                'instansi' => 'Dinas Kependudukan dan Pencatatan Sipil Kota Denpasar',
                'judul_laporan' => 'PELANGI ( PELAYANAN LANGSUNG JADI) DI DESA DAN KELURAHAN SE KOTA DENPASAR',
                'file_laporan' => 'https://drive.google.com/open?id=1S0TRKXAhmSaaXzJfQollT1U33zprm2u5',
                'pesan' => 'Silaturahmi agar tetap terjaga',
                'kesan' => 'Bahagia dapat berkenalan dengan pejabat dari wilayah Indonesia bagian timur',
            ],
            2 => [
                'nama_lengkap' => 'dr. I Nyoman Gunarta, M.P.H.',
                'nip' => '197212132002121005',
                'ndh' => '03',
                'jabgol' => 'Pembina Utama Muda/IVC',
                'alamat' => 'Jln. Sibanggede V, Gg. Gamias No 1, Br. Busana, Desa Sibanggede, Abiansemal, Badung, Bali',
                'hp' => '082147700535',
                'instansi' => 'Dinas Pengendalian Penduduk, Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak Kabupaten Badung',
                'judul_laporan' => 'BADUNG BERGAYA ( Bersama Keluarga Kita Berdaya), Strategi Percepatan Pembangunan Kualitas Keluarga, Pemberdayaan Perempuan dan Perlindungan Anak di Kabupaten Badung',
                'file_laporan' => 'https://drive.google.com/open?id=1Q85GdVenpBFhv488u_f-pds8aubCv2S8',
                'pesan' => 'Life is Change, If You Don’t Change …You Die',
                'kesan' => 'Menarik, dan menambah kompetensi sebagai pejabat eselon II serta selalu berfikir ke arah perubahan yang lebih baik',
            ],
            3 => [
                'nama_lengkap' => 'Aslinda, S.Hut., M.M.',
                'nip' => '197912232005012012',
                'ndh' => '20',
                'jabgol' => 'Kepala Dinas Kependudukan dan Pencatatan Sipil Kabupaten Kayong Utara/IVB',
                'alamat' => 'Jalan Tanjungpura Desa Pangkalan Buton Kecamatan Sukadana Kabupaten Kayong Utara',
                'hp' => '081258081848',
                'instansi' => 'Dinas Kependudukan dan Pencatatan Sipil Kabupaten Kayong Utara',
                'judul_laporan' => 'Percepatan Pelayanan Administrasi Kependudukan “PELITA PONDOK SIDATOKKU”',
                'file_laporan' => 'https://drive.google.com/open?id=1qtXtnvAWPgj8HnFhzKVly08KJlFF5czG',
                'pesan' => 'Keberhasilan datang dari proses yang rumit, tetaplah semangat walaupun harus terjatuh. Jangan menyerah dalam berjuang meraih kemenangan, teruslah berusaha hingga mendapatkan apa yang kamu impikan. Good Luck l💪💪👍👍😍😍',
                'kesan' => 'Sahabat sejati bukan mereka yang memiliki banyak persamaan, akan tetapi adalah mereka yang memiliki pengertian terhadap setiap perbedaan. Dan aku bangga bisa memiliki sahabat/saudara seperti kalian, dan bagiku kalian adalah sahabat/saudara seperjuangan yang terhebat. I miss you guys..... 🥰🥰🥰💪💪💪',
            ],
            4 => [
                'nama_lengkap' => 'ROHANA SRI HARTATI, S.Sos, MM',
                'nip' => '19680603 198909 2 001',
                'ndh' => '24',
                'jabgol' => 'KEPALA BADAN PENELITIAN DAN PENGEMBANGAN KABUPETEN  PESAWARAN',
                'alamat' => 'JLN. RATU DIBALAU, PERUM CITRA BUMI PERMAI BLOK F NO 3 TANJUNG SENANG, KOTA BANDAR LAMPUNG, PROVINSI LAMPUNG',
                'hp' => '081368387043',
                'instansi' => 'PEMERINTAH DAERAH KABUPATEN PESAWARAN',
                'judul_laporan' => 'STRATEGI PENINGKATAN  KELITBANGAN MELALUI RISET KEBIJAKAN PENGEMBANGAN DESA WISATA BUKIT CENDANA DIDESA HARAPAN JAYA  KECAMATAN WAY RATAI, KABUPATEN PESAWARAN, PROVINSI LAMPUNG',
                'file_laporan' => 'https://drive.google.com/open?id=1P2EE4uYHhOc8B4tGAQvktit1miwgiRJY',
                'pesan' => 'Menambah silaturahmi  bertukar pengalaman sesama ASN yang berasal dari Kabupaten dan Kota Seluruh Indonesia',
                'kesan' => 'Dalam Pelatihan Kepemimpinan Nasional Tingkat 2 Angkatan XXIX menambah  Ilmu Pengetahuan dan Keterampilan, terutama  Bagi ASN yang sedang menduduki jabatan Eselon 2 ',
            ],
            5 => [
                'nama_lengkap' => 'Singgih Febriantoro',
                'nip' => '197502271999021001',
                'ndh' => '26',
                'jabgol' => 'Inspektur / IVc',
                'alamat' => 'Jl. Griya sejahtera gg. Pubian no 15b gunung terang, langkapura - Bandarlampung',
                'hp' => '08117231338',
                'instansi' => 'Pemkab Pesawaran, Provinsi Lampung',
                'judul_laporan' => 'Strategi Preventif dalam Pembinaan , Pengawasan Desa Digital dan Desa Wisata di Desa Harapan Jaya Kecamatan Way Ratai kabupaten pesawaran',
                'file_laporan' => 'https://drive.google.com/open?id=1e5YSSBRFwrdw4MzHQepgevxWyRLp2ajs',
                'pesan' => 'Jaga Silaturahmi dan jangan lupa BAHAGIA',
                'kesan' => 'Banyak teman, banyak  macamnya, banyak juga pemikirannya',
            ],
            6 => [
                'nama_lengkap' => 'I Md. Leo Agus Jaya, S.Sos., M.Si.',
                'nip' => '196708041989021004',
                'ndh' => '47',
                'jabgol' => 'Pembina Utama Muda/ IVc',
                'alamat' => 'Jl. Merak No. 28 A, Link. Pendem',
                'hp' => '08123983112',
                'instansi' => 'Satuan Polisi Pamong Praja Kabupaten Jembrana',
                'judul_laporan' => 'Strategi Quick Respon POLPRADES (Polisi Pamong Praja di Desa/Kelurahan)',
                'file_laporan' => 'https://drive.google.com/open?id=1xi7AcxwHyHufsAMR3Ze0CRSngGloBNqw',
                'pesan' => 'Pertahankan semua hal baik, profesionalitas dalam tugas dan pelayanan',
                'kesan' => 'Pelatihan Kepemimpinan Nasional Tingkat II di BKPSDM Provinsi Bali ini sangat luar biasa',
            ],
            7 => [
                'nama_lengkap' => 'Drs. I PUTU DIAN SETIAWAN',
                'nip' => '197310261993021003',
                'ndh' => '29',
                'jabgol' => 'Pembina Utama Muda ( IV/c)',
                'alamat' => 'TABANAN BALI',
                'hp' => '081999843335',
                'instansi' => 'DINAS KOMUNIKASI DAN INFORMATIKA KABUPATEN TABANAN',
                'judul_laporan' => 'Data Digital Tabanan Era Baru',
                'file_laporan' => 'https://drive.google.com/open?id=1iHScNwB3wtJ5xxdO087W9QV0OZdldVEW',
                'pesan' => 'Do it... Or Not @ all .. ( Bahasa Doktrinnya : TERIMA,  .... TERIMA SELURUHNYA.... TOLAK ,..... TOLAK SEMUANYA',
                'kesan' => 'Awalnya malas Ikut Diklat lagi, belajar Lagi Ujian lagi. .  dan pada akhirnya Malas Kembali ke tempat Kerja . inginya selalu bisa happy di kehidupan asrama, senam pagi penuh teriakan Pak Ignatius... Di Kelas aktif bikin Pantun dan saat seminar ada rasa Plong bila sdh selesai ... Eh.  sudah jamnya makan/ snack.   Pemimpin Perubahan harus disiplin Masalah Waktu.. ',
            ],
            8 => [
                'nama_lengkap' => 'Yani Lasama, SKM',
                'nip' => '197412171997032003',
                'ndh' => '09',
                'jabgol' => 'Pembina Tkt I IV b',
                'alamat' => 'Kantor. Jln CutNyak dien Desa Boroko Kec. Kaidipang Kab. Bolaang Mongondow Utara. Sulawesi Utara. Rumah. Jl Pomalango Desa Boroko Kec Kaidipang Kab. Bolaang Mongondow Utara Prop  Sulawesi Utara',
                'hp' => '081354577676',
                'instansi' => 'Dinas PPKBPP dan PA',
                'judul_laporan' => 'Strategi holistik Integratif Cegah Perkawinan Usia Anak di Kabupaten Bolaang Mongondow Utara. ( TAKTIK CERIA) ',
                'file_laporan' => 'https://drive.google.com/open?id=18jMdLg1uVEF9-M17Py4_6ZA0-rO65poL',
                'pesan' => 'Inovasi Pemimpin perubahan Tiada henti untuk kesejahteraan Masyarakat. ',
                'kesan' => 'PKN tkt II Angk XXIX BPSDM Bali Terbaik. ',
            ],
            9 => [
                'nama_lengkap' => 'I GEDE SUKANADA, AP, SH.,M.SI ',
                'nip' => '197602021994121001',
                'ndh' => '15',
                'jabgol' => 'PEMBINA UTAMA MUDA  /IVC',
                'alamat' => 'JALAN KARTINI III B90 TAMAN SEKAR KEDIRI TABANAN BALI',
                'hp' => '081936247788',
                'instansi' => 'SATUAN POLISI PAMONG PRAJA TABANAN BALI',
                'judul_laporan' => 'JAGA TABANAN (JARINGAN SIAGA TABANAN)',
                'file_laporan' => 'https://drive.google.com/open?id=1pjIs7S6haGBPpSS_6bkAXY-Fp8_4PvP1',
                'pesan' => 'Karya Tulis Budi Bakthi',
                'kesan' => 'Persaudaraan Dilandasi Ketulusan',
            ],
            10 => [
                'nama_lengkap' => 'Dra. I Gusti Agung Sri Wetrawati, M.Si',
                'nip' => '196603111995032001',
                'ndh' => '37',
                'jabgol' => 'Kepala Dinas/ Pembina Utama Muda (IV/c)',
                'alamat' => 'Br Parekan Desa Sibanggede Kec. Abiansemal Kab Badung',
                'hp' => '08123608633',
                'instansi' => 'Pemerintah Kota Denpasar',
                'judul_laporan' => '"""PRADANA VASUDHAIVA KUTUMBHAKAM"" Strategi Percepatan Pemberdayaan Perempuan dan Perlindungan Anak Berbasis Budaya di Desa Adat"',
                'file_laporan' => 'https://drive.google.com/open?id=1ewM_AiMHvkEuD_4pEHKQVGA9FdzIHKix',
                'pesan' => 'Kita belajar bersama,  kita bersaudara',
                'kesan' => 'Angkatan XXIX sangat solid',
            ],
            11 => [
                'nama_lengkap' => 'Stengly Langi',
                'nip' => '198309212002121003',
                'ndh' => '50',
                'jabgol' => 'Kepala BKPSDM',
                'alamat' => 'Sitaro Sulut',
                'hp' => '08121329392',
                'instansi' => 'Pemkab Sitaro',
                'judul_laporan' => 'Simpananku',
                'file_laporan' => 'https://drive.google.com/open?id=1zgUr4IufhssOO1sOCUaEQGoVwQrZ_M3g',
                'pesan' => 'Jangan Lupa Bahagia',
                'kesan' => '....',
            ],
            12 => [
                'nama_lengkap' => 'Joickson M Sagune ST MT ',
                'nip' => '196905232003121001',
                'ndh' => '54',
                'jabgol' => 'Kepala BPBD Kabupaten Kepulauan Siau Tagulandang Biaro ',
                'alamat' => 'Jln Nanding no 5',
                'hp' => '082271368384',
                'instansi' => 'BPBD kabupaten Sitaro ',
                'judul_laporan' => 'Pena Siswa (Penanggulangan Bencana berbasis Wilayah) SITARO BISA ',
                'file_laporan' => 'https://drive.google.com/open?id=1AmraqSl9W-crX8niFS4dKWK_5921xpL9',
                'pesan' => 'Jadilah Teladan bagi semua orang ',
                'kesan' => 'Luar biasa ',
            ],
            13 => [
                'nama_lengkap' => 'I Nyoman Suardana,S.Sos.,MM',
                'nip' => '197210101993021002',
                'ndh' => '02',
                'jabgol' => 'Kepala Dinas Perikanan Kab. Badung / IV/c',
                'alamat' => 'Jln Hanoman I no 7 Sempidi,  lingkungan Ubung Sempidi Mengwi Badung',
                'hp' => '081353218359',
                'instansi' => 'Pemerintah Kabupaten Badung',
                'judul_laporan' => 'KASTA ARWANA ( Kawasan Wisata Ikan Air Tawar Badung) Strategi Pengembangan Perbenihan Ikan Air Tawar Mina Agro Wisata ',
                'file_laporan' => 'https://drive.google.com/open?id=1Ggw6RHSczNCfDtCR0EVihZqoKEloV_ep',
                'pesan' => 'Tiap Pertemuam Tentu Ada Perpisahan  tetapi Persaudaraan Harus Tetap Terjalin. KITA BERSAUDARA ',
                'kesan' => 'Semangat Kebersamaan. Baik saat makan, Krida, Belajar bersama',
            ],
            14 => [
                'nama_lengkap' => 'Ida Bagus Benny Pidada Rurus',
                'nip' => '19720924 199803 1 008',
                'ndh' => '39',
                'jabgol' => 'Kepala Dinas/Gol. IV/b',
                'alamat' => 'Jl. Dewi Madri I No.3 Sumerta Kelod, Denpasar, Bali',
                'hp' => '08123912263',
                'instansi' => 'Dinas Penanaman Modal dan PTSP Kota Denpasar',
                'judul_laporan' => 'SIGANAS VASUDHAIVA KUTUMBAKAM',
                'file_laporan' => 'https://drive.google.com/open?id=1dwEXVkBatGkrWwGBnV_qwkJKjkc5Rxvl',
                'pesan' => 'Agar tetap Akrab serta kompak selalu',
                'kesan' => 'Sangat berkesan dan suatu pengalaman yang tidak dapat dilupakan',
            ],
            15 => [
                'nama_lengkap' => 'Chelsia Paputungan, ST',
                'nip' => '19821206 200902 2 001',
                'ndh' => '53',
                'jabgol' => 'Kepala Dinas/ IVa',
                'alamat' => 'Kelurahan Matali, Kec.Kotamobagu Timur-Kota Kotamobagu-SULUT',
                'hp' => '082188945533',
                'instansi' => 'Dinas Perumahan Rakyat dan Kawasan Pemukiman Kotamobagu',
                'judul_laporan' => 'SiPELITA Kotamobagu Terang Bersinar ',
                'file_laporan' => 'https://drive.google.com/open?id=1dm4STJRgCJeqESDMeF6c1WyHD2N8o3pS',
                'pesan' => 'Lebih meningkatkan kwalitas pembelajaran untuk menuju inovasi yang lebih baik',
                'kesan' => 'Sederhana,bersahaja terasa seperti keluarga ',
            ],
            16 => [
                'nama_lengkap' => 'Rinto, SE. M.Si',
                'nip' => '198106012009031002',
                'ndh' => '07',
                'jabgol' => 'Pembina/IVa',
                'alamat' => 'Jalan Antara No  451 Bengkalis',
                'hp' => '08128134456',
                'instansi' => 'Bappeda Kabupaten Bengkalis',
                'judul_laporan' => 'Strategi Penguatan Peran Sektor Swasta Dalam Pembangunan Kabupaten Bengkalis Melalui Forum CSR',
                'file_laporan' => 'https://drive.google.com/open?id=1qkChJqimq8PRlK6fRcL8C02pmXUV85PA',
                'pesan' => 'Tetap bangun silaturahmi',
                'kesan' => 'Bertambah saudara bertambah bahagia',
            ],
            17 => [
                'nama_lengkap' => 'Ketut Nayaka, SH.MH.',
                'nip' => '196809111989031005',
                'ndh' => '49',
                'jabgol' => 'Kepala Biro Organisasi/ IV B',
                'alamat' => 'JL. Griya Nambi Permai II No. 5 Ubung Kaja Denpasar',
                'hp' => '082146142535',
                'instansi' => 'Sekretariat Daerah Provinsi Bali',
                'judul_laporan' => 'STRATEGI AKSELERASI REFORMASI BIROKRASI TERINTEGRASI (STRATA REBORN) PEMERINTAH PROVONSI BALI',
                'file_laporan' => 'https://drive.google.com/open?id=1anznNNp30OPdtLzMR2Syo1CXnfHcLqMh',
                'pesan' => 'Diklat PKN Tk. II Angkatan 29 Tahun 2022, sangat berguna dan menambah pengetahuan serta wawasan dalam meningkatkan kinerja dan Interitas kepemimpinan di Perangkat Daerah masing- masing.',
                'kesan' => 'Sangat senang dan bahagia biasa bergabung dgn temen-temen pejabat dari Provinsi dan Kabupaten/ Kota di Bali dan luar Bali, sehingga menambah persudaraan serta silaturahmi diantara peserta yang selalu kompak dan bersemangat, semoga tali persaudaraan kita tidak pernah putus dan sirna...🙏',
            ],
            18 => [
                'nama_lengkap' => 'I Gede Sukanada, AP, SH.,M.Si',
                'nip' => '197602021994121001',
                'ndh' => '33',
                'jabgol' => 'Kepala Satuan Polisi Pamong Praja Kabupaten Tabanan / Pembina Utama Muda (IV/c)',
                'alamat' => 'Jalan Kartini III B90 Taman Sekar Kediri Tabanan Bali',
                'hp' => '081936247788',
                'instansi' => 'Satuan Polisi Pamong Praja Kabupaten Tabanan ',
                'judul_laporan' => 'JAGA TABANAN (Jaringan Siaga Tabanan)',
                'file_laporan' => 'https://drive.google.com/open?id=1YQhCquKCbbg6tVEm90J61lY2P83hVwdd',
                'pesan' => 'Karya Tulus Budi Bakti ',
                'kesan' => 'Persaudaraan Dilandasi Ketulusan',
            ],
            19 => [
                'nama_lengkap' => 'I Nyoman Gede Anom',
                'nip' => '196806221999031008',
                'ndh' => '48',
                'jabgol' => 'Kadis kesehatan Prov. Bali/IVb',
                'alamat' => 'Jl. Tkd Pancoran, Grahalia Tiying Gading no 5, Denpasar',
                'hp' => '081236666118',
                'instansi' => 'Provinsi Bali',
                'judul_laporan' => 'SITUS BALI',
                'file_laporan' => 'https://drive.google.com/open?id=1W97sNcAPydNRxTx_gRC_w5qYSpuSUSWF',
                'pesan' => 'Salam sehat semuanya',
                'kesan' => 'Sangat  istimewa PKN 2',
            ],
            20 => [
                'nama_lengkap' => 'Drh. I Gusti Ayu Ngurah Raini',
                'nip' => '196711131993032006',
                'ndh' => '36',
                'jabgol' => 'Staf ahli bid. Pembangunan dan Perekonomian',
                'alamat' => 'Jl. Hanoman I no. 34 Br. Ubung Sempidi Badung',
                'hp' => '087860084883',
                'instansi' => 'Pemerintah Kota Denpasar',
                'judul_laporan' => 'Sembagi Arutala melalui spirit Vasudhaiva Kutumbhakam Gerakan Pemberdayaan Masyarakat dalam Pengelolaan Sampah Berbasis Budaya di Desa Adat Kesiman Kertalangu',
                'file_laporan' => 'https://drive.google.com/open?id=1UZkpn1l2yLZ_dnhN595P8xey1P4oI0CU',
                'pesan' => 'Jadilah pemimpin strategis yg baik',
                'kesan' => 'Bersama kalian itu sesuatu banget ',
            ],
            21 => [
                'nama_lengkap' => 'DR. AGUS TONY POPUTRA, SE.,MM.,MA.,Ak',
                'nip' => '196708041993031004',
                'ndh' => '21',
                'jabgol' => 'Pembina Utama Muda/IV C',
                'alamat' => 'BTN Puskopad Perkamil Blok C 1 No 12 Manado',
                'hp' => '+628114301999',
                'instansi' => 'Pemda Kab, Kep, Sitaro Sulawesi Utara',
                'judul_laporan' => 'Kebijakan Holistik Pengentasan Kemiskinan (KOPI-SKIN)',
                'file_laporan' => 'https://drive.google.com/open?id=1StzNI7Idh37vDxHJgXy1TQdLVhWtqJDL',
                'pesan' => 'Jadilah agen pembaharuan sejati untuk Indonesia yang jauh lebih baik',
                'kesan' => 'Everything okay',
            ],
            22 => [
                'nama_lengkap' => 'ANDRIE FRANSUSMAN',
                'nip' => '197902261997111001',
                'ndh' => '56',
                'jabgol' => 'Kepala Dinas (IV/b)',
                'alamat' => 'Jalan Kehutanan No.40 RT.12 RW.06 Kelurahan Pematang Kandis,  Bangko, Kode Pos 37314',
                'hp' => '0813-6623-0600 ',
                'instansi' => 'Dinas Pemperdayaan Masyarakat dan Desa Kabupaten Merangin',
                'judul_laporan' => 'Strategi Pengembangan Potensi Desa Berbasis Pemberdayaan, Konservasi, Edukasi dan Ekonomi Lokal Berkelanjutan (PENTAS DESA)',
                'file_laporan' => 'https://drive.google.com/open?id=1aG8EAYW4Gxtg0EnfqSsCdvomDffPQ9iZ',
                'pesan' => 'Senantiasa Bersyukur',
                'kesan' => 'Kebahagiaan dalam Kebersamaan',
            ],
            23 => [
                'nama_lengkap' => 'Drs. Made Supartawan,.M.M',
                'nip' => '197307071993021002',
                'ndh' => '14',
                'jabgol' => 'Kepala Badan Penelitian Pengembangan dan Inovasi Daerah Kabupaten Buleleng Provinsi Bali ',
                'alamat' => 'Jalan Kumbakarna LC 10 no 45 Desa Bhaktisraga, Kecamatan Buleleng, Bali',
                'hp' => '087762100002',
                'instansi' => 'Pemerintah Kabupaten Buleleng ',
                'judul_laporan' => 'BULELENG INDAH. (STRATEGI MEMBANGUN BULELENG DENGAN INOVASI DAERAH)',
                'file_laporan' => 'https://drive.google.com/open?id=1KK8bvlEzI4JF5zPTXPfvzZLiS8JTf74Z',
                'pesan' => 'Bawa Perubahan dengan Semangat kebersamaan dalam kebhinekaan.',
                'kesan' => 'Terharu dengan kawan baru ',
            ],
            24 => [
                'nama_lengkap' => 'I Putu Kariaman Putra, S.Sos, MM',
                'nip' => '196912311991031053',
                'ndh' => '12',
                'jabgol' => 'Kadis Sosial Kab Buleleng Bali ',
                'alamat' => 'Jln Jalak Putih IV no 15 Kelurahan Banyuasri Kec Buleleng Bali ',
                'hp' => '081239199972',
                'instansi' => 'Jln. Veteran no 7 Buleleng Bali ',
                'judul_laporan' => 'PUSAT KESEJAHTERAAN SOSIAL GESIT CEPAT TANGGAP  ( PUSKESOS GCT ) STRATEGI MEWUJUDKAN BULELENG SATU DATA DATA KESEJAHTERAAN SOSIAL DI KAB BULELENG ',
                'file_laporan' => 'https://drive.google.com/open?id=17oft61MRpoLLzMGKkkflNHjM_lW_qBcz',
                'pesan' => 'Semoga bermanfaat secara khusus bagi warga masyarakat fakir miskin dan warga tdk mampu serta secara umum Pemerintah Pusat, Propinsi dan Pemerintah Daerah Kabupaten Buleleng ',
                'kesan' => 'PKN II telah merubah pola pikir dan pelaksanaan kerja dgn penguatan digital utk mewujudkan tata kelola dan peningkatan kualitas pelayanan publik yang Gesit Cepat Tanggap ( GCT )',
            ],
            25 => [
                'nama_lengkap' => 'Putu Ayu Reika Nurhaeni, S.Sos.,M.A.P.',
                'nip' => '197208091992012002',
                'ndh' => '10',
                'jabgol' => 'Kepala Badan / ( IV/c )',
                'alamat' => 'Jln. Seririt Singaraja, Desa Banjar, Kec. Banjar, Kab. Buleleng',
                'hp' => '081558075125',
                'instansi' => 'Bappeda Kabupaten Buleleng',
                'judul_laporan' => 'TRANSFORMASI EKONOMI SEMESTA BERENCANA DI KABUPATEN BULELENG',
                'file_laporan' => 'https://drive.google.com/open?id=1TnQtM4ZqEj9-KfnQOiSJ9Cf7RjJxIMuA',
                'pesan' => 'Semoga kita selalu dapat memberikan yg TERBAIK dan silaturahmi tetap terjalin.',
                'kesan' => 'Peserta PKN TK. II Angkatan XXIX yg luar biasa, kompak dan penuh kekeluargaan.',
            ],
            26 => [
                'nama_lengkap' => 'Masri Max Kasehung, SH',
                'nip' => '197103242000121002',
                'ndh' => '57',
                'jabgol' => 'Sekretaris DPRD / IVc',
                'alamat' => 'Kab. Kepl. SITARO',
                'hp' => '082187733325',
                'instansi' => 'Pemda Kab.Kep.SITARO',
                'judul_laporan' => 'Money Follow Program DPRD berbasis Alat Kelengkapan.',
                'file_laporan' => 'https://drive.google.com/open?id=1Vn3gnhso2ONnNHUWF5rVTo4EAdYLYc5f',
                'pesan' => 'Tetap semangat dan ceria slalu',
                'kesan' => 'Kebersamaan peserta PKN II Angk. XXIX di kapal bonty cruise ',
            ],
            27 => [
                'nama_lengkap' => 'Ir. I PUTU ADIPTHA EKAPUTRA, ST., MM., IPU.',
                'nip' => '19740610 200003 1 009',
                'ndh' => '13',
                'jabgol' => 'Pembina Tk. I (IV/b)',
                'alamat' => 'Jalan Teratai I/9, Kelurahan Banyuasri, Kabupaten Buleleng, Bali',
                'hp' => '081238000849',
                'instansi' => 'Dinas Pekerjaan Umum dan Tata Ruang Kabupaten Buleleng',
                'judul_laporan' => 'INDAH KBS-IKL (Infrastruktur Daerah Handal Kertih Buleleng Sejahtera - Integrasi Konektivitas dan Lestari Strategi Peningkatan Kualitas Infrastruktur Jalan Melalui Pendekatan Transformasi Ekonomi Kertih Bali)',
                'file_laporan' => 'https://drive.google.com/open?id=1PGMjd6IwfodBalY2OhhJPXcA1KB8YP4b',
                'pesan' => 'Tetap semangat berinovasai dalam melaksanakan tugas',
                'kesan' => 'Bangga bisa berkarya dalam kebersamaan',
            ],
            28 => [
                'nama_lengkap' => 'I NYOMAN PUTRA, SH, MM',
                'nip' => '197905022002121007',
                'ndh' => '34',
                'jabgol' => 'Kepala Dinas Tenaga Kerja / IV/b',
                'alamat' => 'Kantor Dinas Tenaga  Kerja Kabupaten Tabanan, Jl  Wibisana No 2 Tabanan',
                'hp' => '081381468288',
                'instansi' => 'Pemerintah Kabupaten Tabanan',
                'judul_laporan' => '"Sipeta Kerja Desa Tabanan Era Baru "" Strategi Penguatan Tiga Adpek Ketenaga Kerjaan Meliputi Pelatihan, Penempatan Dan Kewirausaan Bagi Masyarakat Desa di Kabupaten Tabanan"',
                'file_laporan' => 'https://drive.google.com/open?id=1YKZC5otF86J6IxCX0GjXBGofy5QJXfg5',
                'pesan' => 'Semoga tali silaturahmi tetap bisa terjalin dan ada kesempatan',
                'kesan' => 'Walau capek tapi menyenangkan',
            ],
            29 => [
                'nama_lengkap' => 'DRA I GAN SUPARTIWI MSi',
                'nip' => '196601281986022003',
                'ndh' => '30',
                'jabgol' => 'Kepala Dinas /IV/c',
                'alamat' => 'Jalan Gunung Agung No 17 Tabanan Bali',
                'hp' => '081237818324',
                'instansi' => 'Dinas Pemberdayaan Masyarakat dan Desa Kabupaten Tabanan Bali',
                'judul_laporan' => 'GUNA DESA ( Geeakan Bersama Menata Desa) Strategi Optimaisasi Peyelenggaraan Pemerintahan Desa di Kabupaten Tabanan',
                'file_laporan' => 'https://drive.google.com/open?id=1YutOqVLrDHLeabHUvnKIhcVK93IS_9xZ',
                'pesan' => 'Semoga kita semua selalu sehat dan bisa berjumpa kembali',
                'kesan' => 'Indahnya kebersamaan di PKN II Angkt XXIX',
            ],
            30 => [
                'nama_lengkap' => 'Drs. I Gde Eka Sudarwitha, S.Sos, M.Si',
                'nip' => '197401211993021001',
                'ndh' => '4',
                'jabgol' => 'Kepala Dinas Kebudayaan Kab. Badung, Bali / IVb',
                'alamat' => 'Banjar Pundung, Desa Pangsan, Kec. Petang. Badung',
                'hp' => '081338512134',
                'instansi' => 'Pemerintah Kabupaten Badung',
                'judul_laporan' => 'Banjar Menari Strategi Pengembangan Sekaa dan Sanggar Seni sebagai Pusat Aktifitas dan Kreatifitas Budaya Masyarakat pada Tingkat Banjar di Kabupaten Badung',
                'file_laporan' => 'https://drive.google.com/open?id=1so3py0lBtvaq5WdrxFEiUrJjFXLMv1jU',
                'pesan' => 'Jalinan komunikasi diantara alumni PKN II Ang. XXIX agar terus.dipelihara sehingga sesama alumni dapat saling support.',
                'kesan' => 'Bangga pernah mengikutinya.',
            ],
            31 => [
                'nama_lengkap' => 'Komang Budhi Argawa, S.H., M.Si',
                'nip' => '197109011998031009',
                'ndh' => '1',
                'jabgol' => 'Kadis PMD Kabupaten Badung/IVc',
                'alamat' => 'Jl. Badak Sari iI No. 6 Denpasar',
                'hp' => '081805449333',
                'instansi' => 'Dinas PMD Kabupaten Badung',
                'judul_laporan' => 'PUSAKA SAKTI BADUNG (Pemberdayaan Usaha Krama BUM Desa sebagai Strategi Kerja Kolaboratif Terpadu Inklusi Keuangan Badung)',
                'file_laporan' => 'https://drive.google.com/open?id=1PRa0o83xILCdUqe59IO09x-8c-4FuArW',
                'pesan' => 'Penyelenggaraan PKN Tingkat II Angkatan XXIX Tahun 2022 minimal dapat dipertahankan atau ditingkatkan agar dapat menghadapi tantangan global yang semakin kompleks   ',
                'kesan' => 'Penyelenggaraan PKN Tingkat II Angkatan XXIX Tahun 2022 sudah berjalan cukup baik',
            ],
            32 => [
                'nama_lengkap' => 'Ardiansyah, ST. MT',
                'nip' => '198606252010011012',
                'ndh' => '06',
                'jabgol' => 'Kepala Dinas PUPR Bengkalis (IVa)',
                'alamat' => 'Jalan Karimun Kec. Bengkalis Kab. Bengkalis Prop. Riau',
                'hp' => '081268686842',
                'instansi' => 'Dinas PUPR Kab. Bengkalis',
                'judul_laporan' => 'Sistem Infomasi Pemeliharaan Jalan dan Jembatan Berbasis Masyarakat (SIMPEJA - BERMASA)',
                'file_laporan' => 'https://drive.google.com/open?id=1ydYsFs3rJ3hjDyANlEOmRNV4omm3EzhO',
                'pesan' => 'Tetap berfikiran positif walaupun situasi atau kehidupan sulit.',
                'kesan' => 'Perbedaan Bukan membuat kita terpecah belah tapi memahami setiap perbedaan',
            ],
            33 => [
                'nama_lengkap' => 'I Gst Pt Ngurah Darma Utama, AP.M.Si',
                'nip' => '197408071993111001',
                'ndh' => '20',
                'jabgol' => 'Kadis Pendidikan Tabanan/IV (c)',
                'alamat' => 'Jl.Merdeka No.10 Tabanan Bali',
                'hp' => '081338280909',
                'instansi' => 'DINAS PENDIDIKAN KABUPATEN TABANAN',
                'judul_laporan' => 'Mutiara Pancasila  Menuju Tabanan Era Baru',
                'file_laporan' => 'https://drive.google.com/open?id=1oMaDbvYD1wHIcQcE6yios_18gBuf4mGx',
                'pesan' => 'Lakukan yang terbaik untuk kehidupan melalui belajar dengan siapapun , kapanpun dan dimanapun untuk perubahan',
                'kesan' => 'Idealisme yang hanya sebatas wacana dalam lembaga pendidikan akan menjadi virus kecil yang berujung pada kehancuran',
            ],
            34 => [
                'nama_lengkap' => 'Salim Muhaimin, S.Pd.M.Si',
                'nip' => '197011071997021003',
                'ndh' => '51',
                'jabgol' => 'Kepala Dinas Pendidikan dan Kebudayaan Kabupaten Pesisir Selatan Sumatera BaratPembina/ Utama Muda/IV.C',
                'alamat' => 'Jl. Perintis Kemerdekaan Painan',
                'hp' => '082268881050',
                'instansi' => 'Dinas Pendidikan dan Kebudayaan',
                'judul_laporan' => 'Strategi Pengembangan Diri Siswa Melalui Program Nagari Bersekolah (PRONASA)',
                'file_laporan' => 'https://drive.google.com/open?id=1bBLm5GzLY7pSKcpb3xgrVK-s8S-bt9m9',
                'pesan' => 'Inovasi Untuk Kemajuan Bangsa',
                'kesan' => 'Maju Bersama Hebat Semua',
            ],
            35 => [
                'nama_lengkap' => 'Drs. Dewa Made Sudiarta, M.Si',
                'nip' => '197410141993111001',
                'ndh' => '15',
                'jabgol' => 'Kadis Perdagangan Perindustrian Koperasi dan Usaha Kecil Menengah/ IV/b',
                'alamat' => 'Jl. Pulau Seribu Perum Griya Mandala Blok B No. 125 Kel. Penarukan Lingk. Ketewel Singaraja - BALI',
                'hp' => '081933050581',
                'instansi' => 'Dinas Perdagangan Perindustrian Koperasi dan UKM',
                'judul_laporan' => 'Strategi Pemberdayaan UMKM Naik Kelas Melalui Kelembagaan Bersama Satu Pintu Yang Terintegrasi Kolaboratif dan Berkelanjutan',
                'file_laporan' => 'https://drive.google.com/open?id=1kPezpicnuQJioHwdgiMsI5ryqmcuKPCS',
                'pesan' => '""" berikan yang terbaik "" "',
                'kesan' => 'PKN II 29  Mantap dan Luar biasa',
            ],
            36 => [
                'nama_lengkap' => 'TAMSIR.,SH.,MM.,',
                'nip' => '196703121988031003',
                'ndh' => '52',
                'jabgol' => 'Kepala BKPSDM Kab. Pesisir Selatan. Prov. Sumatera Barat',
                'alamat' => 'Jln. Jayapura F/21 Aratek Ulak Karang Selatan',
                'hp' => '081372526067',
                'instansi' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                'judul_laporan' => '"""DIGITALISASI MANAJEMEN KEPEGAWAIAN"" STRATEGI mewujudkan Optimalisasi Pengelolaan Kepegawaian Berbasis Digital Di Kabupaten Persisir Selatan"',
                'file_laporan' => 'https://drive.google.com/open?id=1Z1jisPfrx042nHboQinKx_-tuPEM-anB',
                'pesan' => 'Agar Persahabatan/Persaudaraan ini Tetap Hidup di Ingatan Kita.',
                'kesan' => 'Canda Tawa Teman2 yang Tak Pernah Hilang.',
            ],
            37 => [
                'nama_lengkap' => 'Drs . I Wayan Sudiana',
                'nip' => '196605041993031020',
                'ndh' => '35',
                'jabgol' => 'Kepala BKPSDM / IV c',
                'alamat' => 'Jalan warmadewa 14c Denpasar',
                'hp' => '082237783085',
                'instansi' => 'Pemerintah Kota Denpasar',
                'judul_laporan' => 'Nayaka Praja  Vasudhaiva Kutumbhakam Menuju Tatwamasi',
                'file_laporan' => 'https://drive.google.com/open?id=1Erq7x_N5KYlCH8AQ5neBlIV8C1oWAAtz',
                'pesan' => 'Datang dan Pergi untuk sebuah pengabdian',
                'kesan' => 'Pengalaman yang luar biasa ,teman teman semua peduli dengan sesama',
            ],
            38 => [
                'nama_lengkap' => 'Suhendri',
                'nip' => '197004041996011002',
                'ndh' => '40',
                'jabgol' => 'Kepala Badan (IV c)',
                'alamat' => 'Perumahan Vila Kenali Permai - Mayang Mangurai - Kota Jambi ',
                'hp' => '081366565970',
                'instansi' => 'Bappeda Kota Jambi',
                'judul_laporan' => 'Strategi Perencanaan Pengembangan Kepariwisataan melalui inovasi Simpang Keris ',
                'file_laporan' => 'https://drive.google.com/open?id=1AlNE17jVFBQriPxXUYTKmyK029CLIVCi',
                'pesan' => 'Jadikanlah sabar sebagai penolong',
                'kesan' => 'Senang dan bangga pernah ada bersama di PKN 2 Angkatan XXIX - 2022 Bali',
            ],
        ];

        foreach ($peserta as $r) {
            Peserta::create($r);
        }

        User::create([
            'nama' => 'admin',
            'email' => 'admin@pkn.com',
            'password' => Hash::make('ateblukup'),
        ]);
    }
}
